server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mystore?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mystorelogin
  cloud:
    nacos:
      server-addr: localhost:8848
  profiles:
    include: feign
  redis:
    host: localhost
    port: 6379

mybatis:
  # 配置MyBatis的xml配置文件路径
   mapper-locations: classpath:mapper/*.xml
    # 配置XML映射文件中指定的实体类别名路径
    # type-aliases-package: com.example.demo3.pojo
    # 开启驼峰uName自动映射到u_name
    # map-underscore-to-camel-case: true

